version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - django-network
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
      - ./static_volume:/app/static
      - ./media_volume:/app/media
    networks:
      - django-network
    depends_on:
      - db
  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network
volumes:
  media_volume:
  static_volume:
